#!/bin/bash
# -*- coding:utf-8 -*-
##
#                                                                                            
#    dP                                                                                                                                                              
#    88                                                                                                                                                              
#    88 .d8888b. d888888b dP    dP    .d8888b. .d8888b. 88d888b. 88d888b.    88d8b.d8b. .d8888b. dP   .dP .d8888b.    88d8b.d8b. .d8888b. dP    dP .d8888b. .d8888b. 
#    88 88'  `88    .d8P' 88    88    88'  `"" 88'  `88 88'  `88 88'  `88    88'`88'`88 88'  `88 88   d8' 88ooood8    88'`88'`88 88'  `88 88    88 Y8ooooo. 88ooood8 
#    88 88.  .88  .Y8P    88.  .88    88.  ... 88.  .88 88       88.  .88    88  88  88 88.  .88 88 .88'  88.  ...    88  88  88 88.  .88 88.  .88       88 88.  ... 
#    dP `88888P8 d888888P `8888P88    `88888P' `88888P' dP       88Y888P'    dP  dP  dP `88888P' 8888P'   `88888P'    dP  dP  dP `88888P' `88888P' `88888P' `88888P' 
#                              .88                               88                                                                                                  
#                          d8888P                                dP                                                                                                  
#
#    https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=Nancyj-Fancy&text=lazy%20corp%20move%20mouse
#
# @Author	  Lazy Corp
# @Created	  20/05/2024
###

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT
function ctrl_c() {
    echo "| User abort"
}

INSTALL_PATH=~/bin/lazycorp/lzvenv

pushd $INSTALL_PATH
source ./bin/activate
python3 ../move
deactivate
popd
#EOF
###