#!/bin/bash
# -*- coding:utf-8 -*-
##
#
#    dP                                                                                          dP                     
#    88                                                                                          88                     
#    88 .d8888b. d888888b dP    dP    .d8888b. .d8888b. 88d888b. 88d888b.    .d8888b. .d8888b. d8888P dP    dP 88d888b. 
#    88 88'  `88    .d8P' 88    88    88'  `"" 88'  `88 88'  `88 88'  `88    Y8ooooo. 88ooood8   88   88    88 88'  `88 
#    88 88.  .88  .Y8P    88.  .88    88.  ... 88.  .88 88       88.  .88          88 88.  ...   88   88.  .88 88.  .88 
#    dP `88888P8 d888888P `8888P88    `88888P' `88888P' dP       88Y888P'    `88888P' `88888P'   dP   `88888P' 88Y888P' 
#                              .88                               88                                            88       
#                          d8888P                                dP                                            dP       
#
#    https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=Nancyj-Fancy&text=lazy%20corp%20setup
#
# @Author	  Lazy Corp
# @Created	  20/05/2024
###

INSTALL_PATH=~/bin/lazycorp
venv_name=lzvenv

sudo apt install -y xprintidle

[[ -d $INSTALL_PATH ]] || mkdir -p $INSTALL_PATH
cp move* requirements.txt config.yaml $INSTALL_PATH/
ln -s ~/bin/lazycorp/movemouse ~/bin/movemouse

pushd $INSTALL_PATH
virtualenv $venv_name
source $venv_name/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
popd

#EOF
###